services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: talk_encrypted_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres/talk_encrypted_development
      DB_HOST: postgres
      DB_USER: postgres
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - postgres

  worker:
    build: .
    command: bin/rails solid_queue:start
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres/talk_encrypted_development
      DB_HOST: postgres
      DB_USER: postgres
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - postgres

volumes:
  postgres_data:
